//////////////////////////////////////////////////////////////////////////////
// Arma 3 Mission Skeleton by longbow
// version 1.3
// This is an autogenerated file
//////////////////////////////////////////////////////////////////////////////
// waitUntil {!isNull (findDisplay 46)};

// enableRadio false;
// player setSpeaker "NoVoice";


// Спавним игрока в случайном доме в деревне-спавне
// _housesArray = nearestObjects [player, ["house"], 100];
// _randomHouse = selectRandom _housesArray;
// _positionsArray = [_randomHouse] call BIS_fnc_buildingPositions;
// _randomPosition = selectRandom _positionsArray;
// player setPos _randomPosition;

// Меню для Зевсов
_addMoney10000 = ["AddMoney","Добавить себе 10000 рублей","\A3\ui_f\data\map\markers\military\destroy_CA.paa",{[player, 10000] call grad_moneymenu_fnc_addFunds},{true}] call ace_interact_menu_fnc_createAction;
[["ACE_ZeusActions"], _addMoney10000] call ace_interact_menu_fnc_addActionToZeus;
_addMoney1000 = ["AddMoney","Добавить себе 1000 рублей","\A3\ui_f\data\map\markers\military\destroy_CA.paa",{[player, 1000] call grad_moneymenu_fnc_addFunds},{true}] call ace_interact_menu_fnc_createAction;
[["ACE_ZeusActions"], _addMoney1000] call ace_interact_menu_fnc_addActionToZeus;
_addMoney500 = ["AddMoney","Добавить себе 500 рублей","\A3\ui_f\data\map\markers\military\destroy_CA.paa",{[player, 500] call grad_moneymenu_fnc_addFunds},{true}] call ace_interact_menu_fnc_createAction;
[["ACE_ZeusActions"], _addMoney500] call ace_interact_menu_fnc_addActionToZeus;
_removeTrash = ["RemoveTrash","Удалить мусор на базе","\A3\ui_f\data\map\groupicons\waypoint.paa",{
  _trashArray = gradTrigger nearObjects ["GroundWeaponHolder", 100];
  for "_i" from 0 to count _trashArray - 1 do {
    deleteVehicle (_trashArray select _i);
  };
},{true}] call ace_interact_menu_fnc_createAction;
[["ACE_ZeusActions"], _removeTrash] call ace_interact_menu_fnc_addActionToZeus;



// Ролл
_rollAction=["RollAction","Бросить кубик","\A3\ui_f_orange\data\cfgmarkers\dangerousforces_ca.paa",{
    	_random = str ceil random 6;
      [player, _random, 30] call {
        params ["_unit", "_text", "_distance"];
        [_unit, _text] remoteExec ["globalChat", call BIS_fnc_listPlayers select { _x distance _unit < _distance }];
      };
  },
  {
    true
    }
    ] call ace_interact_menu_fnc_createAction;
[player, 1, ["ACE_SelfActions"],_rollAction]call ace_interact_menu_fnc_addActionToObject;



// Инкогнито для independent
if (playerSide == independent) then {
  player setVariable ["isSneaky",true,true];
};


// Инкогнито
if (player getVariable ["isSneaky",false]) then {
    [player] execVM "modules\INC_undercover\Scripts\initUCR.sqf";
};


// Терентьев, Волков, Тимошенко, Коськин
// ["76561198040777688", "76561198806755399", "76561198856869973", "76561198394783916"];

_uidArray = ["76561198040777688", "76561198806755399"];
private _uid = getPlayerUID player;
private _uidCheck = _uidArray find _uid;
private _playerObject = _uid call BIS_fnc_getUnitByUID;
private _isCurator = _playerObject call BIS_fnc_isCurator;
if (_uidCheck != -1) then
{
  _assignCurator=["AssignCurator","Zeus","\A3\ui_f_orange\data\cfgmarkers\culturalproperty_ca.paa",{
    try {
      [moduleCurator] remoteExec ["unassignCurator", 2];
      [player, moduleCurator] remoteExec["assignCurator", 2];
      } catch
      {
        systemChat str _exception;
      };
  },
  {
    true
    }
    ] call ace_interact_menu_fnc_createAction;
    [_playerObject,1,["ACE_SelfActions"],_assignCurator]call ace_interact_menu_fnc_addActionToObject;
};









// Any uniform
// Any uniform
// Any uniform
// Any uniform
// Any uniform
fnc_otherUnif = {  
  params ["_type","_return"];  
  if (_type == 0) exitWith {  
    MGI_button = _return #1; false  
  };  
  if (_type == 1 and !isnil "MGI_button" && {MGI_button == 1}) then {  
    disableSerialization;  
    _control = _return select 0;  
    _index = _return select 1;  
    private _idc = ctrlIDC _control;  
    private _text = lbText [_idc, _index];  
    private _picture = lbPicture [_idc,_index];  
    private _uniforms = ("getText (_x >> 'displayName') == _text && getNumber (_x >> 'ItemInfo' >> 'type') == 801" configClasses (configFile >> "CfgWeapons")); 
 
    if (_uniforms isEqualType [] && {!(_uniforms isEqualTo [])}) then {  
      [_idc,_text,_picture,_index,_uniforms] spawn {  
        params ["_idc","_text","_picture","_index","_uniforms",["_selectedUnif",""],"_unifConts",["_uniformObject",objNull],"_otherItems","_g0"];  
        private _currentUnif = uniform player;  
        private _currentInvent = uniformItems player;  
        _currentInvent = (_currentInvent arrayIntersect _currentInvent) apply {private _v= _x;[_x]+[{_v isEqualTo _x} count _currentInvent]}; 
        private _selectedUnif = ((_uniforms select {toLower (gettext (_x >> "picture")) splitString "\"joinString "\" == _picture}) apply {configName _x}); 
        if (_selectedUnif isEqualTo []) exitWith {};
  
        if !(pl_container isKindOf "CAManBase") then {  
          _unifConts = (everyContainer pl_container select {getNumber (configFile >> "CfgWeapons" >> _x #0 >> 'ItemInfo' >> 'type') == 801});
          _uniformObject = objNull;
          private ["_cnt","_selectedCfg"];
          scopeName "main";
          for "_i" from 0 to count _selectedUnif -1 do {
            _cnt = 0;
            _selectedCfg = _selectedUnif #_i; 
            for "_j" from 0 to _index do {  
              if (lbText [_idc,_j] == _text) then {  
                _cnt = _cnt +1;
                _uniformObject = _unifConts select {_selectedCfg == (_x #0)} select (_cnt -1) select 1;
                if (!isnil "_uniformObject" && {!isNull _uniformObject}) then {
                  _selectedUnif = _selectedCfg;
                  breakTo "main"
                };
              };
            };
            _uniformObject = objNull;
          };  
        } else {
          _selectedUnif = _selectedUnif #0;  
          _uniformObject = uniformContainer pl_container  
        }; 
 
        if (!isNull _uniformObject && !(player isUniformAllowed _selectedUnif)) then { 
           
          private _itemsAndMags = (_uniformObject call MGI_orderItsAndMgs) params ["_selectedItems","_selectedMags"]; 
           
          if !(pl_container isKindOf "CAmanbase" or isNull pl_container) then {  
            private _its = getItemCargo pl_container; 
            private _mgs = magazinesAmmoCargo pl_container; 
            private _unifItems = _unifConts apply {_x #0}; 
            private _vestConts = (everyContainer pl_container select {getNumber (configFile >> "CfgWeapons" >> _x #0 >> 'ItemInfo' >> 'type') == 701}); 
            private _vestItems = _vestConts apply {_x #0}; 
            _otherItems = +(_its #0) - _unifItems - _vestItems; 
            _otherItems = _otherItems apply {[_x,_its #1#(_its #0 find _x)]}; 
            private _conts = _unifConts + _vestConts; 
            for '_i' from 0 to count _Conts -1 do { 
              if (_conts #_i #1 == _uniformObject) exitWith { 
                _conts deleteAt _i 
              }; 
            }; 
           
            pl_container setVariable ["MGIallContForWear",[]]; 
            { 
              private _itsAndMgs = ((_x #1) call MGI_orderItsAndMgs) params ["_its","_mgs"]; 
              (pl_container getVariable "MGIallContForWear") pushBack [_x #0,_its,_mgs]; 
            } forEach _conts; 
            _g0 = pl_container; 
            clearItemCargoGlobal _g0; 
          } else { 
            _g0 = createVehicle ['WeaponHolderSimulated_Scripted', (player modelToWorld [0,1,1]), [], 0, 'CAN_COLLIDE'] 
          }; 
 
          player forceAddUniform _selectedUnif;  
          private _unif = uniformContainer player; 
          {_unif addItemCargoGlobal [_x#0,_x#1]} count _selectedItems; 
          {_unif addMagazineAmmoCargo [_x#0,_x#2,_x#1]} count _selectedMags;  
          call {  
            if (pl_container isKindOf "CAManBase") exitWith {  
              removeUniform pl_container  
            };  
            {  
              _x params ["_cont",["_it",[]],["_mag",[]]];  
              pl_container addItemCargoGlobal [_cont,1];  
              private _createdCont = pl_container call MGI_lastCont; 
              {_createdCont addItemCargoGlobal [_x#0,_x#1]} count _it; 
              {_createdCont addMagazineAmmoCargo [_x#0,_x#2,_x#1]} count _mag;  
            } forEach (pl_container getVariable "MGIallContForWear"); 
            {_g0 addItemCargoGlobal [_x #0,_x #1]} forEach _otherItems;  
          };  
           
          _g0 addItemCargoGlobal [_currentUnif,1]; 
          _lastCont = _g0 call MGI_lastCont;  
          {_lastCont addItemCargoGlobal [_x #0,_x #1]} forEach _currentInvent;  
          if (_g0 isKindOf "WeaponHolderSimulated" && {(count itemCargo _g0 + count magazineCargo _g0 + count weaponCargo _g0 + count backpackCargo _g0) == 0}) then {  
            deleteVehicle _g0  
          };  
        };  
      }; 
    };  
  MGI_button = 0; false  
  };  
}; 
 
MGI_orderItsAndMgs = compileFinal " 
  params [['_uniformObject', objNull,[objNull]]]; 
  private _items = getItemCargo _uniformObject; 
  private _mags = magazinesAmmoCargo _uniformObject; 
  private _selectedItems = (_items #0) apply {[_x,_items #1#(_items #0 find _x)]}; 
  private _selectedMags = (_mags arrayintersect _mags) apply {private _v= _x;_x+[{_v isEqualTo _x} count _mags]}; 
  [_selectedItems,_selectedMags]; 
"; 
 
MGI_lastCont = compileFinal "  
  params [['_cont',objNull]];  
  private '_lastCont';  
   _invent = (everyContainer _cont - (everyBackpack _cont apply {[typeOf _x,_x]}));  
   if !(_invent isEqualTo []) then {  
    _lastCont = _invent select (count _invent -1) select 1;  
   } else {  
    _lastCont = _cont;  
   };  
   _lastCont  
";  
  
player addEventHandler ["InventoryOpened", {  
  params ["_unit", "_container"];  
  pl_container = _container;  
  [] spawn {  
    waitUntil {!(isNull findDisplay 602)};  
    disableSerialization;  
    {(findDisplay 602 displayCtrl _x) ctrlAddEventHandler ["MouseButtonClick", "[0,_this] call fnc_otherUnif"]} forEach [632,640];  
    {(findDisplay 602 displayCtrl _x) ctrlAddEventHandler ["LBSelChanged", "[1,_this] spawn fnc_otherUnif"]} forEach [632,640];  
  };  
}];


// Any uniform
// Any uniform
// Any uniform
// Any uniform
// Any uniform

// Запрещаем воровать из рюкзаков живых людей
player addEventHandler ["InventoryOpened",{
params ["_unit","_container"];
_override = false;
_allUnitBackpackContainers = allUnits select {alive _x} apply {backpackContainer _x};
if (_container in _allUnitBackpackContainers) then {
//  systemChat "Ща как по ебальничку дам уебище";
  _override = true;
};
_override
}];


// Удаляем труп игрока после смерти
player addEventHandler ["Respawn",{ 
	params ["_newObject","_oldObject"];
  _newObject = (_this select 0);
  _oldObject = (_this select 1);
  [_oldObject] remoteExec ["removeAllWeapons"];
  [_oldObject] remoteExec ["removeVest"];
  [_oldObject] remoteExec ["removeHeadgear"];
  [_oldObject] remoteExec ["removeGoggles"];
	// removeAllWeapons _oldObject;
  // removeVest _oldObject;
  // removeHeadgear _oldObject;
  // deleteVehicle _oldObject; 
}];




// Ломаем окна
/*
if (isDedicated || !hasInterface) exitWith {};
if (!isNil "ifx_windowBreak_handle") then {
  [ifx_windowBreak_handle] call CBA_fnc_removePerFrameHandler;
  ifx_windowBreak_handle = nil;
};

ifx_windowBreak_handle = [{
  if (!isNil "ifx_windowBreak_subHandle") then {
    if (!scriptDone ifx_windowBreak_subHandle) exitWith {};
  };

  if_windowBreak_subHandle = [] spawn {
    private _player = call CBA_fnc_currentUnit;
    _buildings = _player nearObjects ["Building", 125];

    {
      private _building = _x;
      if (isNull _building) then {continue};
      if (_building getVariable ["ifx_windowBreak_registered", false]) then {continue};


      _selections = (_building selectionNames "HitPoints") select {_x find "glass" > -1};
      {
        private _helperPos = AGLtoASL (_building modelToWorld (_building selectionPosition _x));
        private _helperObject = "ACE_LogicDummy" createVehicleLocal [0,0,0];
        _helperObject setPosASL _helperPos;
        
        private _breakWindowAction = [
          "Break_Window",
          localize "STR_TAG_breakWindow",
          ["", "#C4D4E0"],
          {
            params ["_target", "_player", "_params"];
            _params params ["_building", "_selectionName"];
            _building setHit [_selectionName, 1, true];
          }, // statement
          {
            params ["_target", "_player", "_params"];
            _params params ["_building", "_selectionName"];
            (_building getHit _selectionName) < 1;
            // true;
          }, // condition
          {}, // child code
          [_building, _x], // params
          [0,0,0], // position
          2, // distance
          //[showDisabled,enableInside,canCollapse,runOnHover,doNotCheckLOS] // special params
          [false, true, true, false, true]
        ] call ace_interact_menu_fnc_createAction;

        // [typeOf _building, 0, [], _breakWindowAction] call ace_interact_menu_fnc_addActionToClass;
        [_helperObject, 0, [], _breakWindowAction] call ace_interact_menu_fnc_addActionToObject;

      } forEach _selections;

      _building setVariable ["ifx_windowBreak_registered", true];
    } forEach _buildings;
  };
}, 10] call CBA_fnc_addPerFrameHandler;
*/



_uidArray = [
	// [
	// 	"76561198040777688",
	// 	"Демьян Терентьев",
  //   [["rhs_weap_akm","","","",["rhs_30Rnd_762x39mm_bakelite",30],[],""],[],[],["UK3CB_CHD_B_U_CombatUniform_04",[["ACE_EarPlugs",1]]],["rhs_6b2_chicom",[["rhs_mag_f1",1,1],["rhs_mag_rdg2_white",3,1],["rhs_30Rnd_762x39mm_bakelite",20,30]]],["UK3CB_B_O_Backpack_Radio_Chem_OLI",[["ACE_splint",4],["ACE_bloodIV",5],["ACE_bloodIV_250",5],["ACE_bloodIV_500",5],["ACE_EntrenchingTool",1],["ACE_morphine",10],["ACE_tourniquet",8],["ACE_fieldDressing",15],["ACE_epinephrine",5],["ToolKit",1],["ACE_DefusalKit",1],["ACE_packingBandage",15],["ACE_elasticBandage",15],["ACE_surgicalKit",1]]],"UK3CB_H_Beret_Officer_Red_Star","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak_2","ItemCompass","",""]]
	// ],
	[
		"76561198856869973",
		"Артём Тимошенко",
		[["rhs_weap_ak104_zenitco01_b33_grip1","rhs_acc_dtk4screws","","rhsusf_acc_ACOG_USMC",["rhs_30Rnd_762x39mm_polymer",30],[],"rhsusf_acc_grip1"],["rhs_weap_rpg26","","","",[],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["UK3CB_CHD_B_U_CombatUniform_07",[["ACE_elasticBandage",20],["ACE_splint",4],["ACE_morphine",5],["ACE_epinephrine",5]]],["UK3CB_TKA_O_V_6b23_ml_Oli_02",[["30Rnd_762x39_AK12_Mag_F",10,30]]],["UK3CB_ION_B_B_ASS_OLI_01",[["ACE_SpraypaintBlack",1],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_Flashlight_MX991",1],["ACE_RangeCard",1],["ACE_Cellphone",1],["ACE_EntrenchingTool",1],["rhs_mag_f1",5,1],["rhs_mag_rdg2_white",5,1],["rhsusf_mag_7x45acp_MHP",5,7],[["rhs_weap_rpg26","","","",[],[],""],2]]],"rhs_6b27m_green","UK3CB_G_Balaclava",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","TFAR_microdagr","rhsusf_ANPVS_14"]]
	],
	[
		"76561198170743341",
		"Кирилл Металлов",
		[["rhs_weap_asval_grip1","","","rhs_acc_pso1m21",["rhs_20rnd_9x39mm_SP6",20],[],"rhs_acc_grip_rk6"],[],[],["UK3CB_LSM_B_U_CombatSmock_07",[["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_morphine",5],["ACE_elasticBandage",15],["ACE_tourniquet",4],["ACE_splint",4]]],["rhs_6b23_6sh116_flora",[["rhs_mag_f1",1,1],["rhs_20rnd_9x39mm_SP6",1,20]]],["UK3CB_B_Invisible",[["ACE_bloodIV_500",5],["ACE_personalAidKit",2],["rhs_20rnd_9x39mm_SP6",24,20],["rhs_mag_f1",4,1]]],"rhs_6b26_bala","UK3CB_G_Ballistic_Black_Tactical_Gloves_Green",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak_3","ItemCompass","TFAR_microdagr",""]]
	],
	[
		"76561198954068907",
		"Иван Дубов",
		[["rhs_weap_ak74m_zenitco01_grip1","rhs_acc_dtk4short","acc_pointer_IR","rhs_acc_ekp1",["rhs_30Rnd_545x39_7N22_AK",30],[],"rhs_acc_grip_ffg2"],[],["rhs_weap_pya","","","",["rhs_mag_9x19_17",17],[],""],["UK3CB_LSM_B_U_CombatSmock_33",[["rhs_mag_9x19_7n31_17",3,17],["rhs_grenade_khattabka_vog25_mag",3,1]]],["rhs_6b13_Flora_crewofficer",[["ACE_personalAidKit",1],["ACE_tourniquet",4],["rhs_30Rnd_545x39_7N22_AK",2,30],["rhs_grenade_khattabka_vog25_mag",1,1]]],["UK3CB_B_Invisible",[["ACE_bloodIV",5],["ACE_fieldDressing",20],["ACE_surgicalKit",1],["ACE_splint",4],["ToolKit",1],["ACE_EntrenchingTool",1],["ACE_Clacker",1],["UK3CB_ANA_B_H_Beret_GRN",1],["rhs_ec400_mag",6,1]]],"UK3CB_ANA_B_H_6b27m_WDL","UK3CB_G_Balaclava2_BLK",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]]
	],
	[
		"76561198810670428",
		"Николай Язвинский",
		[["rhs_weap_ak104_zenitco01_b33_grip1","rhs_acc_dtk4screws","","rhsusf_acc_ACOG_USMC",["rhs_30Rnd_762x39mm_polymer",30],[],"rhsusf_acc_grip1"],["rhs_weap_rpg26","","","",[],[],""],["rhsusf_weap_m1911a1","","","",["rhsusf_mag_7x45acp_MHP",7],[],""],["UK3CB_LSM_B_U_CombatSmock_31",[["ACE_elasticBandage",20],["ACE_splint",4],["ACE_morphine",5],["ACE_epinephrine",5]]],["rhs_6b13_Flora_6sh92",[["30Rnd_762x39_AK12_Mag_F",10,30]]],["UK3CB_LSM_B_B_Sidor_WDL_RIF",[["ACE_SpraypaintBlack",1],["ACE_microDAGR",1],["ACE_Kestrel4500",1],["ACE_Flashlight_MX991",1],["ACE_RangeCard",1],["ACE_Cellphone",1],["ACE_EntrenchingTool",1],["rhs_mag_f1",5,1],["rhs_mag_rdg2_white",5,1],["rhsusf_mag_7x45acp_MHP",5,7],[["rhs_weap_rpg26","","","",[],[],""],2]]],"UK3CB_ANA_B_H_6b27m_WDL","UK3CB_G_Balaclava",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","TFAR_microdagr","rhsusf_ANPVS_14"]]
	],
	[
		"76561199028171073",
		"Аблахат Кенесбек",
		[["rhs_weap_pkp","","","rhs_acc_ekp8_02",["rhs_100Rnd_762x54mmR",99],[],""],["rhs_weap_rpg26","","","",[],[],""],["rhsusf_weap_MP7A2_folded","","","",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],["UK3CB_LSM_B_U_CombatSmock_31",[["ACE_elasticBandage",20],["ACE_splint",4],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_EarPlugs",1]]],["rhs_6b13_Flora_6sh92",[]],["UK3CB_LSM_B_B_Sidor_WDL_RIF",[["ACE_SpraypaintBlack",1],["ACE_Kestrel4500",1],["ACE_Flashlight_MX991",1],["ACE_RangeCard",1],["ACE_Cellphone",1],["ACE_EntrenchingTool",1],["ACE_microDAGR",1],["rhs_mag_f1",5,1],["rhs_mag_rdg2_white",5,1],["150Rnd_762x54_Box",3,150],["rhsusf_mag_40Rnd_46x30_AP",2,40]]],"UK3CB_ANA_B_H_6b27m_WDL","UK3CB_G_Bandanna_aviator_green_check",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","TFAR_microdagr","rhsusf_ANPVS_14"]]		
	]
];

_allMarshals = [marshalWEST, marshalEAST, marshalINDEPENDENT];
{
	private _unit = _x;
  _equipmentTree = ["EquipmentTree","Личные экипировки","\a3\ui_f\data\igui\cfg\simpletasks\types\rearm_ca.paa", 
    { 
      nil 
    },
    {
      true
    }
  ] call ace_interact_menu_fnc_createAction;
  [_unit, 0, ["ACE_MainActions"], _equipmentTree] call ace_interact_menu_fnc_addActionToObject;
	{
		_uid = _x select 0;
		_name = _x select 1;
		_set = _x select 2;
		// if (_playerUID != _uid) exitWith {
		// 	// systemChat format ["ты не %1", _name];
		// };
		_givePersonalEquipment = ["_uid", format ["Получить личную экипировку: %1", _name],"\a3\ui_f\data\igui\cfg\simpletasks\types\rearm_ca.paa",
			// Action
			{
				params ["_target", "_player", "_params"];
				_params params ["_uid", "_name", "_set"];
        _playerUID = getPlayerUID _player;
				if (_playerUID != _uid) exitWith {
					hintSilent "Некорректный игрок";
				};
				_playerCash = [_player] call grad_lbm_fnc_getFunds;
				if (_playerCash < 500) exitWith {
					hintSilent "Недостаточно денег. Необходимо минимум 500Р."
				};
				[_player, -500] call grad_moneymenu_fnc_addFunds;
				hintSilent "Вы приобрели личный комплект за 500Р";
				_player setUnitLoadout _set;
			},
			// Condition
			{
				true
			},
			{},
			// Params
			[_uid, _name, _set],
			[0,0,0], 
			100
		] call ace_interact_menu_fnc_createAction;

		[_unit, 0, ["ACE_MainActions", "EquipmentTree"], _givePersonalEquipment] call ace_interact_menu_fnc_addActionToObject;
	} forEach _uidArray;
} forEach _allMarshals;






